// Generated by CoffeeScript 1.7.1
var $checkboxes;

$checkboxes = $("input:checkbox");

$checkboxes.on("change", function() {
  var opts;
  opts = getCarFilterOptions();
  updateCars(opts);
  getContinentTitle(opts);
  $("#sorting-selector option[value='default']").attr("selected", "selected");
  return getFinalPrice(opts);
});

$("#sorting-selector").on("change", function() {
  var opts, sortKey;
  sortKey = $("#sorting-selector option:selected").text();
  opts = getCarFilterOptions();
  updateSorting(sortKey, opts);
  getContinentTitle(opts);
});

$(document).ready(function() {
  var record;
  record = 0;
  updateCars();
  getContinentTitle();
  getFinalPrice();
  return $("#cars tbody").html(makeTable());
});

//# sourceMappingURL=runner.map
